// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "opusminer_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// load_data
void load_data(Rcpp::GenericVector input);
RcppExport SEXP opusminer_load_data(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::GenericVector >::type input(inputSEXP);
    load_data(input);
    return R_NilValue;
END_RCPP
}
// load_data_whole
void load_data_whole(Rcpp::GenericVector tidList, int numItems, int numTrans);
RcppExport SEXP opusminer_load_data_whole(SEXP tidListSEXP, SEXP numItemsSEXP, SEXP numTransSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::GenericVector >::type tidList(tidListSEXP);
    Rcpp::traits::input_parameter< int >::type numItems(numItemsSEXP);
    Rcpp::traits::input_parameter< int >::type numTrans(numTransSEXP);
    load_data_whole(tidList, numItems, numTrans);
    return R_NilValue;
END_RCPP
}
// opusHelper
Rcpp::GenericVector opusHelper(Rcpp::NumericVector k_, Rcpp::LogicalVector args);
RcppExport SEXP opusminer_opusHelper(SEXP k_SEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type k_(k_SEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(opusHelper(k_, args));
    return rcpp_result_gen;
END_RCPP
}
