# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_tids <- function() {
    .Call('opusminer_get_tids', PACKAGE = 'opusminer')
}

.opusHelper <- function(tidList, numItems, numTrans, k_, args) {
    .Call('opusminer_opusHelper', PACKAGE = 'opusminer', tidList, numItems, numTrans, k_, args)
}

