# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_data <- function(input) {
    invisible(.Call('opusminer_load_data', PACKAGE = 'opusminer', input))
}

load_data_whole <- function(tidList, numItems, numTrans) {
    invisible(.Call('opusminer_load_data_whole', PACKAGE = 'opusminer', tidList, numItems, numTrans))
}

.opusHelper <- function(k_, args) {
    .Call('opusminer_opusHelper', PACKAGE = 'opusminer', k_, args)
}

